name: Build and Deploy to Cloud Run

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    env:
      IMAGE_NAME: gcr.io/${{ secrets.PROJECT_ID }}/app

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install package
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: "Create env file"
        run: |
          echo "${{ secrets.ENV_FILE }}" > .env

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: "${{ secrets.WORKLOAD_IDENTITY_PROVIDER_LOCATION }}"
          service_account: "${{ secrets.SERVICE_ACCOUNT }}@${{ secrets.PROJECT_ID }}.iam.gserviceaccount.com"

      - name: Configure Docker
        run: gcloud auth configure-docker --quiet

      - name: Build Docker image
        run: docker build . -t $IMAGE_NAME

      - name: Push Docker image
        run: docker push $IMAGE_NAME

      - id: deploy
        name: Deploy Docker image
        uses: "google-github-actions/deploy-cloudrun@v0"
        with:
          image: ${{ env.IMAGE_NAME }}
          region: asia-southeast1
          service: paivis-bot
          flags: --port=3000

      - name: Test URL
        run: curl "${{ steps.deploy.outputs.url }}"
