name: Testing

on: pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install package
        run: bun install

      - name: "Create env file"
        run: |
          touch .env
          echo API_KEY=${{ secrets.API_KEY }} >> .env
          echo LINE_CHANNEL_ACCESS_TOKEN=${{ secrets.LINE_CHANNEL_ACCESS_TOKEN }} >> .env
          echo LINE_CHANNEL_SECRET=${{ secrets.LINE_CHANNEL_SECRET }} >> .env
          echo NOTION_TOKEN=${{ secrets.NOTION_TOKEN }} >> .env
          echo NOTION_EXPENSE_DATABASE_ID=${{ secrets.NOTION_EXPENSE_DATABASE_ID }} >> .env

      - name: Check lint
        run: bun eslint src/**/*.ts

      - name: Run unit test
        run: bun test
